allowBuilds:
  '@heroui/shared-utils': true
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  prisma: true
  prisma-zod-generator: true
  sharp: true
  unrs-resolver: true
  '@duckarchive/framework': true
overrides:
  "react-aria": "3.51.0"
  "react-stately": "3.49.0"
  "@react-stately/color": "3.8.0"
  "@react-types/color": "3.2.0"