onlyBuiltDependencies:
  - "@duckarchive/framework"
  - "@duckarchive/map"
  - "@duckarchive/prisma"
  - "@heroui/shared-utils"
  - "@parcel/watcher"
  - "@prisma/client"
  - "@prisma/engines"
  - "@swc/core"
  - esbuild
  - prisma
  - prisma-zod-generator
  - sharp
  - unrs-resolver"