-- ДАС: catalog reconciliation (mbv3). Generated by research/tools/generate.py from ../../2026-08-22-das-tom3/config.json.
BEGIN;
CREATE TEMP TABLE arch AS SELECT id FROM archives WHERE code = 'ДАС';
DO $$ BEGIN IF (SELECT count(*) FROM arch) <> 1 THEN RAISE EXCEPTION 'archive not found'; END IF; END $$;

-- A. справи in the catalog but missing in the DB
CREATE TEMP TABLE mf(fond text, inv text, code text, title text, tags text[], years text);
INSERT INTO mf VALUES ('11','1','2','Метрична книга. Церква Севастопольського морського шпиталю в ім’я Святих Апостолів Петра та Павла, м. Севастополь',ARRAY['метрична книга','народження','шлюб','смерть']::text[],'1820-1820'),
('11','1','5','Метрична книга. Церква Севастопольського морського шпиталю в ім’я Святих Апостолів Петра та Павла, м. Севастополь',ARRAY['метрична книга','народження','шлюб','смерть']::text[],'1822-1822'),
('11','1','9','Метрична книга. Церква Севастопольського морського шпиталю в ім’я Святих Апостолів Петра та Павла, м. Севастополь',ARRAY['метрична книга','народження','шлюб','смерть']::text[],'1825-1825'),
('11','1','11','Метрична книга. Церква Севастопольського морського шпиталю в ім’я Святих Апостолів Петра та Павла, м. Севастополь',ARRAY['метрична книга','народження','шлюб','смерть']::text[],'1826-1826'),
('11','1','18','Метрична книга. Церква Севастопольського морського шпиталю в ім’я Святих Апостолів Петра та Павла, м. Севастополь',ARRAY['метрична книга','народження','смерть']::text[],'1839-1839'),
('11','1','36','Метрична книга. Церква Севастопольського морського шпиталю в ім’я Святих Апостолів Петра та Павла, м. Севастополь',ARRAY['метрична книга','народження','смерть']::text[],'1856-1856');
INSERT INTO files (code, full_code, title, tags, inventory_id)
SELECT mf.code, 'ДАС' || '-' || mf.fond || '-' || mf.inv || '-' || mf.code, mf.title, mf.tags, i.id
FROM mf JOIN fonds fo ON fo.code = mf.fond JOIN arch ON arch.id = fo.archive_id JOIN inventories i ON i.fond_id = fo.id AND i.code = mf.inv
WHERE NOT EXISTS (SELECT 1 FROM files x WHERE x.inventory_id = i.id AND x.code = mf.code);
INSERT INTO file_years (file_id, start_year, end_year) SELECT f.id, split_part(r, '-', 1)::int, split_part(r, '-', 2)::int
FROM mf JOIN files f ON f.full_code = 'ДАС' || '-' || mf.fond || '-' || mf.inv || '-' || mf.code, unnest(string_to_array(mf.years, ',')) r
WHERE mf.years <> '' AND NOT EXISTS (SELECT 1 FROM file_years y WHERE y.file_id = f.id) ON CONFLICT DO NOTHING;
DO $$ BEGIN IF (SELECT count(*) FROM mf JOIN files f ON f.full_code = 'ДАС' || '-' || mf.fond || '-' || mf.inv || '-' || mf.code) <> (SELECT count(*) FROM mf) THEN RAISE EXCEPTION 'A: not all files created (inventory missing?)'; END IF; END $$;

-- H. year ranges: DB span is a strict subset of the catalog's → catalog ranges
CREATE TEMP TABLE hy(full_code text, old text, new text); INSERT INTO hy VALUES ('ДАС-30-1-36','1896-1896','1843-1843,1896-1896');
CREATE TEMP TABLE hf AS SELECT hy.*, f.id AS file_id FROM hy JOIN files f ON f.full_code = hy.full_code;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM hf WHERE (SELECT min(start_year)||'-'||max(end_year) FROM file_years y WHERE y.file_id = hf.file_id) IS DISTINCT FROM hf.old) THEN RAISE EXCEPTION 'H: DB years changed since snapshot'; END IF; END $$;
DELETE FROM file_years y USING hf WHERE y.file_id = hf.file_id; INSERT INTO file_years (file_id, start_year, end_year) SELECT hf.file_id, split_part(r, '-', 1)::int, split_part(r, '-', 2)::int FROM hf, unnest(string_to_array(hf.new, ',')) r;

-- G. placeholder titles → catalog church names
CREATE TEMP TABLE gt(full_code text, title text); INSERT INTO gt VALUES ('ДАС-3-1-1','Метрична книга. Церква Дунайської гребельної флотилії, м. Ізмаїл'),
('ДАС-3-1-2','Метрична книга. Церква Дунайської гребельної флотилії, м. Ізмаїл'),
('ДАС-3-1-3','Метрична книга. Церква Дунайської гребельної флотилії, м. Ізмаїл'),
('ДАС-3-1-4','Метрична книга. Церква Дунайської гребельної флотилії, м. Ізмаїл'),
('ДАС-3-1-5','Метрична книга. Церква Дунайської гребельної флотилії, м. Ізмаїл'),
('ДАС-3-1-6','Метрична книга. Церква Дунайської гребельної флотилії, м. Ізмаїл'),
('ДАС-3-1-7','Метрична книга. Церква Дунайської гребельної флотилії, м. Ізмаїл'),
('ДАС-3-1-8','Метрична книга. Церква Дунайської гребельної флотилії, м. Ізмаїл'),
('ДАС-3-1-9','Метрична книга. Церква Дунайської гребельної флотилії, м. Ізмаїл'),
('ДАС-3-1-10','Метрична книга. Церква Дунайської гребельної флотилії, м. Ізмаїл'),
('ДАС-3-1-11','Метрична книга. Церква Дунайської гребельної флотилії, м. Ізмаїл'),
('ДАС-3-1-12','Метрична книга. Церква Дунайської гребельної флотилії, м. Ізмаїл'),
('ДАС-3-1-13','Метрична книга. Церква Дунайської гребельної флотилії, м. Ізмаїл'),
('ДАС-3-1-14','Метрична книга. Церква Дунайської гребельної флотилії, м. Ізмаїл'),
('ДАС-3-1-15','Метрична книга. Церква Дунайської гребельної флотилії, м. Ізмаїл'),
('ДАС-3-1-16','Метрична книга. Церква Дунайської гребельної флотилії, м. Ізмаїл'),
('ДАС-3-1-17','Метрична книга. Церква Дунайської гребельної флотилії, м. Ізмаїл'),
('ДАС-3-1-18','Метрична книга. Церква Дунайської гребельної флотилії, м. Ізмаїл'),
('ДАС-3-1-19','Метрична книга. Церква Дунайської гребельної флотилії, м. Ізмаїл'),
('ДАС-3-1-20','Метрична книга. Церква Дунайської гребельної флотилії, м. Ізмаїл'),
('ДАС-3-1-21','Метрична книга. Церква Дунайської гребельної флотилії, м. Ізмаїл'),
('ДАС-3-1-22','Метрична книга. Церква Дунайської гребельної флотилії, м. Ізмаїл'),
('ДАС-3-1-23','Метрична книга. Церква Дунайської гребельної флотилії, м. Ізмаїл'),
('ДАС-3-1-24','Метрична книга. Церква Дунайської гребельної флотилії, м. Ізмаїл'),
('ДАС-3-1-26','Метрична книга. Церква Дунайської гребельної флотилії, м. Ізмаїл'),
('ДАС-3-1-27','Метрична книга. Церква Дунайської гребельної флотилії, м. Ізмаїл'),
('ДАС-3-1-28','Метрична книга. Церква Дунайської гребельної флотилії, м. Ізмаїл'),
('ДАС-3-1-29','Метрична книга. Церква Дунайської гребельної флотилії, м. Ізмаїл'),
('ДАС-3-1-30','Метрична книга. Церква Дунайської гребельної флотилії, м. Ізмаїл'),
('ДАС-3-1-25','Метрична книга. Церква Дунайської гребельної флотилії, м. Ізмаїл');
UPDATE files f SET title = gt.title FROM gt WHERE f.full_code = gt.full_code AND f.title ~* '^Метрична книга$';
UPDATE files f SET title = regexp_replace(f.title, '^Метрична книга\. (Метричні книги )', '\1') FROM gt WHERE f.full_code = gt.full_code AND f.title ~ '^Метрична книга\. Метричні книги ';

SELECT 'A created' k, count(*) FROM (SELECT 1) x WHERE false UNION ALL SELECT 'A created', count(*) FROM mf JOIN files f ON f.full_code = 'ДАС' || '-' || mf.fond || '-' || mf.inv || '-' || mf.code UNION ALL SELECT 'H re-dated', count(*) FROM hf UNION ALL SELECT 'G retitled', count(*) FROM gt JOIN files f ON f.full_code = gt.full_code WHERE f.title = gt.title;
