"""python3 generate.py <config.json> — builds <out>/migration.sql (+CSVs, README) for one archive from work/<book>-<ARCH>/.
config: {"archive","books":[...],"out","placeholder_regex":"^Метрична книга$"|null,"exclude_codes":[],"typos":{fond:fond},
         "dups":[[src_full_code,dst_full_code]],"apply_years_subset":true}"""
import json, csv, re, os, sys
from collections import OrderedDict
cfg = json.load(open(sys.argv[1])); H = os.path.dirname(os.path.abspath(__file__)); R = os.path.dirname(H)
A = cfg["archive"]; OUT = cfg["out"]; os.makedirs(OUT, exist_ok=True)
q = lambda s: "'" + str(s).replace("'", "''") + "'"
arr = lambda t: "ARRAY[" + ",".join(q(x) for x in t) + "]::text[]" if t else "'{}'::text[]"
yrs = lambda r: ",".join(f"{a}-{b}" for a, b in r)
KIND = {5: "народження", 6: "шлюб", 7: "розлучення", 8: "смерть"}
def tags_for(v):
    t = [KIND[x] for x in v["kinds"] if x in KIND]; lab = " ".join(v["labels"]).lower()
    if "обшук" in lab: t.append("шлюбні обшуки")
    if "сповід" in lab: t.append("сповідальні відомості")
    return (["метрична книга"] + t) if t else []
def title_for(church, tags, labels):
    if "метрична книга" in tags: return f"Метрична книга. {church}"
    lab = " ".join(labels).lower()
    if "обшук" in lab: return f"Книга шлюбних обшуків. {church}"
    if "сповід" in lab: return f"Сповідальні відомості. {church}"
    return f"{labels[0]}. {church}" if labels else church
def ranges(ys):
    ys = sorted(set(ys)); out = []
    for y in ys:
        if out and y == out[-1][1] + 1: out[-1][1] = y
        else: out.append([y, y])
    return out
mf, mt, my, mtitle, fy, gen, hy = [], [], [], [], [], [], []
PR_ALL = OrderedDict(); rows_all = {}
for book in cfg["books"]:
    W = f"{R}/work/{book}-{A}"; act = json.load(open(f"{W}/actions-{A}.json"))
    PR = {}
    for k0, v in json.load(open(f"{W}/{A}.json"))["refs"].items():
        f, op, sp = k0.split("-"); f = cfg.get("typos", {}).get(f, f); PR.setdefault(f"{f}-{op.upper()}-{sp.upper()}", v)
    PR_ALL.update(PR)
    rows = {(r[0], r[1], r[2]): r for r in csv.reader(open(f"{W}/{A}-files.tsv"), delimiter="\t", quoting=csv.QUOTE_NONE)}; rows_all.update(rows)
    seen_mf = {x[1] for x in mf}
    for inv in cfg.get("create_inventories", []):
        for k, v in PR.items():
            if k.startswith(inv + "-") and k not in seen_mf:
                act["missing_files"].append(dict(code=k, church=v["church"], tags=tags_for(v), years=ranges(v["years"])))
    for m in act["missing_files"]:
        if m["code"] in cfg.get("exclude_codes", []) or m["code"] in seen_mf: continue
        f, op, sp = m["code"].split("-"); v = PR.get(m["code"], {})
        mf.append((A, m["code"], f, op, sp, title_for(m["church"], m["tags"], v.get("labels", [])), m["tags"], yrs(m["years"])))
    for m in act["add_mk_tag"]: mt.append((f"{A}-{m['code']}", m["tags"]))
    for m in act["fill_years"]: my.append((f"{A}-{m['code']}", yrs(m["years"])))
    for m in act["fill_title"]:
        v = PR[m["code"]]; mtitle.append((f"{A}-{m['code']}", title_for(m["church"], tags_for(v), v["labels"])))
    for m in act["fond_years"]: fy.append((A, m["code"], m["years"]))
    if cfg.get("apply_years_subset"):
        for d in act["year_disagree"]:
            a = list(map(int, d["db"].split("-"))); b = list(map(int, d["catalog"].split("-")))
            if b[1] - b[0] <= 60 and a[0] >= b[0] and a[1] <= b[1] and (a != b):
                hy.append((f"{A}-{d['code']}", d["db"], yrs(ranges(PR[d["code"]]["years"]))))
    if cfg.get("placeholder_regex"):
        rx = re.compile(cfg["placeholder_regex"], re.I)
        for k, v in PR.items():
            r = rows.get(tuple(k.split("-")))
            if r and rx.match(r[3] or "") and "метрична книга" in (tags_for(v) or ["метрична книга"]): gen.append((f"{A}-{k}", f"Метрична книга. {v['church']}"))
# dedupe
mt = list(OrderedDict((k, t) for k, t in mt).items()); gen = list(OrderedDict(gen).items()); hy = list(OrderedDict((k, (a, b)) for k, a, b in hy).items())
S = [f"-- {A}: catalog reconciliation ({', '.join(cfg['books'])}). Generated by research/tools/generate.py from {sys.argv[1]}.", "BEGIN;",
     f"CREATE TEMP TABLE arch AS SELECT id FROM archives WHERE code = {q(A)};", "DO $$ BEGIN IF (SELECT count(*) FROM arch) <> 1 THEN RAISE EXCEPTION 'archive not found'; END IF; END $$;"]
P = S.append
if cfg.get("create_inventories"):
    P("\n-- A0. описи the catalog cites that the DB lacks")
    P("CREATE TEMP TABLE mi(fond text, inv text); INSERT INTO mi VALUES " + ",".join(f"({q(x.split('-')[0])},{q(x.split('-')[1])})" for x in cfg["create_inventories"]) + ";")
    P("INSERT INTO inventories (code, fond_id) SELECT mi.inv, fo.id FROM mi JOIN fonds fo ON fo.code = mi.fond JOIN arch ON arch.id = fo.archive_id WHERE NOT EXISTS (SELECT 1 FROM inventories i WHERE i.fond_id = fo.id AND i.code = mi.inv);")
if mf:
    P("\n-- A. справи in the catalog but missing in the DB")
    P("CREATE TEMP TABLE mf(fond text, inv text, code text, title text, tags text[], years text);")
    P("INSERT INTO mf VALUES " + ",\n".join(f"({q(f)},{q(o)},{q(s)},{q(t)},{arr(tg)},{q(y)})" for _, _, f, o, s, t, tg, y in mf) + ";")
    P(f"""INSERT INTO files (code, full_code, title, tags, inventory_id)
SELECT mf.code, {q(A)} || '-' || mf.fond || '-' || mf.inv || '-' || mf.code, mf.title, mf.tags, i.id
FROM mf JOIN fonds fo ON fo.code = mf.fond JOIN arch ON arch.id = fo.archive_id JOIN inventories i ON i.fond_id = fo.id AND i.code = mf.inv
WHERE NOT EXISTS (SELECT 1 FROM files x WHERE x.inventory_id = i.id AND x.code = mf.code);""")
    P(f"""INSERT INTO file_years (file_id, start_year, end_year) SELECT f.id, split_part(r, '-', 1)::int, split_part(r, '-', 2)::int
FROM mf JOIN files f ON f.full_code = {q(A)} || '-' || mf.fond || '-' || mf.inv || '-' || mf.code, unnest(string_to_array(mf.years, ',')) r
WHERE mf.years <> '' AND NOT EXISTS (SELECT 1 FROM file_years y WHERE y.file_id = f.id) ON CONFLICT DO NOTHING;""")
    P(f"DO $$ BEGIN IF (SELECT count(*) FROM mf JOIN files f ON f.full_code = {q(A)} || '-' || mf.fond || '-' || mf.inv || '-' || mf.code) <> (SELECT count(*) FROM mf) THEN RAISE EXCEPTION 'A: not all files created (inventory missing?)'; END IF; END $$;")
if mt:
    P("\n-- B. «метрична книга» + kind tags")
    P("CREATE TEMP TABLE mt(full_code text, tags text[]); INSERT INTO mt VALUES " + ",\n".join(f"({q(k)},{arr(t)})" for k, t in mt) + ";")
    P("UPDATE files f SET tags = (SELECT array_agg(DISTINCT x) FROM unnest(f.tags || mt.tags) x) FROM mt WHERE f.full_code = mt.full_code AND NOT ('метрична книга' = ANY(f.tags));")
if my:
    P("\n-- C. bare years"); P("CREATE TEMP TABLE my(full_code text, years text); INSERT INTO my VALUES " + ",".join(f"({q(k)},{q(y)})" for k, y in my) + ";")
    P("INSERT INTO file_years (file_id, start_year, end_year) SELECT f.id, split_part(r, '-', 1)::int, split_part(r, '-', 2)::int FROM my JOIN files f ON f.full_code = my.full_code, unnest(string_to_array(my.years, ',')) r WHERE NOT EXISTS (SELECT 1 FROM file_years y WHERE y.file_id = f.id) ON CONFLICT DO NOTHING;")
if mtitle:
    P("\n-- C. bare titles"); P("CREATE TEMP TABLE mtt(full_code text, title text); INSERT INTO mtt VALUES " + ",\n".join(f"({q(k)},{q(t)})" for k, t in mtitle) + ";")
    P("UPDATE files f SET title = mtt.title FROM mtt WHERE f.full_code = mtt.full_code AND coalesce(f.title, '') = '';")
if fy:
    P("\n-- D. fond year ranges"); P("CREATE TEMP TABLE fy(fond text, s int, e int); INSERT INTO fy VALUES " + ",".join(f"({q(c)},{s},{e})" for _, c, ys in fy for s, e in ys) + ";")
    P("INSERT INTO fond_years (fond_id, start_year, end_year) SELECT fo.id, fy.s, fy.e FROM fy JOIN fonds fo ON fo.code = fy.fond JOIN arch ON arch.id = fo.archive_id WHERE NOT EXISTS (SELECT 1 FROM fond_years y WHERE y.fond_id = fo.id) ON CONFLICT DO NOTHING;")
if cfg.get("dups"):
    P("\n-- E. glued duplicates (identical title + span as a catalog sibling)")
    P("CREATE TEMP TABLE mg(src text, dst text); INSERT INTO mg VALUES " + ",".join(f"({q(s)},{q(d)})" for s, d in cfg["dups"]) + ";")
    P("CREATE TEMP TABLE g AS SELECT m.*, s.id AS src_id, d.id AS dst_id FROM mg m JOIN files s ON s.full_code = m.src JOIN files d ON d.full_code = m.dst;")
    P("DO $$ BEGIN IF (SELECT count(*) FROM g) <> (SELECT count(*) FROM mg) THEN RAISE EXCEPTION 'E: source or target missing'; END IF; END $$;")
    P("""DO $$ BEGIN IF EXISTS (SELECT 1 FROM g JOIN files s ON s.id = g.src_id JOIN files d ON d.id = g.dst_id WHERE s.title IS DISTINCT FROM d.title OR (SELECT min(start_year)||'-'||max(end_year) FROM file_years WHERE file_id = s.id) IS DISTINCT FROM (SELECT min(start_year)||'-'||max(end_year) FROM file_years WHERE file_id = d.id)) THEN RAISE EXCEPTION 'E: not an exact duplicate'; END IF; END $$;""")
    P("DELETE FROM online_copies oc USING g WHERE oc.file_id = g.src_id AND EXISTS (SELECT 1 FROM online_copies d WHERE d.file_id = g.dst_id AND d.resource_id = oc.resource_id AND d.url = oc.url AND d.parsed = oc.parsed);")
    P("UPDATE online_copies oc SET file_id = g.dst_id FROM g WHERE oc.file_id = g.src_id;")
    P("INSERT INTO file_authors (file_id, author_id) SELECT g.dst_id, fa.author_id FROM file_authors fa JOIN g ON fa.file_id = g.src_id ON CONFLICT DO NOTHING; DELETE FROM file_authors fa USING g WHERE fa.file_id = g.src_id;")
    P("UPDATE file_actions x SET file_id = g.dst_id FROM g WHERE x.file_id = g.src_id; DELETE FROM files f USING g WHERE f.id = g.src_id;")
if hy:
    P("\n-- H. year ranges: DB span is a strict subset of the catalog's → catalog ranges")
    P("CREATE TEMP TABLE hy(full_code text, old text, new text); INSERT INTO hy VALUES " + ",\n".join(f"({q(k)},{q(a)},{q(b)})" for k, (a, b) in hy) + ";")
    P("CREATE TEMP TABLE hf AS SELECT hy.*, f.id AS file_id FROM hy JOIN files f ON f.full_code = hy.full_code;")
    P("DO $$ BEGIN IF EXISTS (SELECT 1 FROM hf WHERE (SELECT min(start_year)||'-'||max(end_year) FROM file_years y WHERE y.file_id = hf.file_id) IS DISTINCT FROM hf.old) THEN RAISE EXCEPTION 'H: DB years changed since snapshot'; END IF; END $$;")
    P("DELETE FROM file_years y USING hf WHERE y.file_id = hf.file_id; INSERT INTO file_years (file_id, start_year, end_year) SELECT hf.file_id, split_part(r, '-', 1)::int, split_part(r, '-', 2)::int FROM hf, unnest(string_to_array(hf.new, ',')) r;")
if gen:
    P("\n-- G. placeholder titles → catalog church names")
    P("CREATE TEMP TABLE gt(full_code text, title text); INSERT INTO gt VALUES " + ",\n".join(f"({q(k)},{q(t)})" for k, t in gen) + ";")
    P(f"UPDATE files f SET title = gt.title FROM gt WHERE f.full_code = gt.full_code AND f.title ~* {q(cfg['placeholder_regex'])};")
    P("UPDATE files f SET title = regexp_replace(f.title, '^Метрична книга\\. (Метричні книги )', '\\1') FROM gt WHERE f.full_code = gt.full_code AND f.title ~ '^Метрична книга\\. Метричні книги ';")
P("\nSELECT 'A created' k, count(*) FROM (SELECT 1) x WHERE false" + (f" UNION ALL SELECT 'A created', count(*) FROM mf JOIN files f ON f.full_code = {q(A)} || '-' || mf.fond || '-' || mf.inv || '-' || mf.code" if mf else "") +
  (" UNION ALL SELECT 'B tagged', count(*) FROM mt JOIN files f ON f.full_code = mt.full_code WHERE 'метрична книга' = ANY(f.tags)" if mt else "") +
  (" UNION ALL SELECT 'D fond-year rows', count(*) FROM fy JOIN fonds fo ON fo.code = fy.fond JOIN arch ON arch.id = fo.archive_id JOIN fond_years y ON y.fond_id = fo.id" if fy else "") +
  (" UNION ALL SELECT 'E removed', count(*) FROM mg WHERE NOT EXISTS (SELECT 1 FROM files WHERE full_code = mg.src)" if cfg.get("dups") else "") +
  (" UNION ALL SELECT 'H re-dated', count(*) FROM hf" if hy else "") +
  (" UNION ALL SELECT 'G retitled', count(*) FROM gt JOIN files f ON f.full_code = gt.full_code WHERE f.title = gt.title" if gen else "") + ";")
open(f"{OUT}/migration.sql", "w").write("\n".join(S) + "\n")
with open(f"{OUT}/01-missing-files.csv", "w", newline="") as fh: w = csv.writer(fh); w.writerow(["archive","code","fond","inventory","file","title","tags","years"]); w.writerows([(a,c,f,o,s,t,"|".join(tg),y) for a,c,f,o,s,t,tg,y in mf])
with open(f"{OUT}/02-tags.csv", "w", newline="") as fh: w = csv.writer(fh); w.writerow(["full_code","tags"]); w.writerows([(k,"|".join(t)) for k,t in mt])
with open(f"{OUT}/03-titles.csv", "w", newline="") as fh: w = csv.writer(fh); w.writerow(["full_code","title"]); w.writerows(gen + mtitle)
with open(f"{OUT}/04-years.csv", "w", newline="") as fh: w = csv.writer(fh); w.writerow(["full_code","db_before","catalog"]); w.writerows([(k,a,b) for k,(a,b) in hy])
print(f"{A}: A {len(mf)} | B {len(mt)} | C years {len(my)} titles {len(mtitle)} | D {len(fy)} | E {len(cfg.get('dups', []))} | H {len(hy)} | G {len(gen)}")
