"""Class E: replace DB year ranges with the catalog's where the DB range does not cover the catalog range."""
import json, csv, re, os
H = os.path.dirname(os.path.abspath(__file__)); A = f"{H}/analysis"
PR = json.load(open(f"{A}/catalog-parsed.json"))["refs"]
tsv = lambda n: list(csv.reader(open(f"{A}/{n}"), delimiter="\t", quoting=csv.QUOTE_NONE))
DFL = {(r[0], r[1], r[2]): r for r in tsv("db-files.tsv")}
q = lambda s: "'" + s.replace("'", "''") + "'"
def ranges(years):
    ys = sorted(set(years)); out = []
    for y in ys:
        if out and y == out[-1][1] + 1: out[-1][1] = y
        else: out.append([y, y])
    return out
def yrs_db(s):
    o = set()
    for a, b in re.findall(r"(\d{4})-(\d{4})", s): o.update(range(int(a), int(b) + 1))
    return o
rows = []
for k, v in PR.items():
    f, op, sp = k.split("-")
    if f in ("1", "74"): continue
    d = DFL.get((f, op, sp))
    if not d or not d[4].strip() or not v["years"]: continue
    py, dy = set(v["years"]), yrs_db(d[4])
    if min(dy) <= min(py) and max(py) <= max(dy): continue
    rows.append((f"ДАДоО-{f}-{op}-{sp}", d[4], ",".join(f"{a}-{b}" for a, b in ranges(py))))
rows.sort(key=lambda r: (int(r[0].split("-")[1]), int(re.sub(r"\D", "", r[0].split("-")[3]) or 0)))
with open(f"{H}/05-years.csv", "w", newline="") as fh:
    w = csv.writer(fh); w.writerow(["full_code", "db_years_before", "catalog_years"]); w.writerows(rows)
S = ["-- Class E: DB year ranges replaced by the catalog's (input: 05-years.csv). Generated by generate_e.py.", "BEGIN;",
     "CREATE TEMP TABLE ey(full_code text, old text, new text);",
     "INSERT INTO ey VALUES " + ",\n".join(f"({q(a)},{q(b)},{q(c)})" for a, b, c in rows) + ";",
     "CREATE TEMP TABLE ef AS SELECT ey.*, f.id AS file_id FROM ey JOIN files f ON f.full_code = ey.full_code;",
     "DO $$ BEGIN IF (SELECT count(*) FROM ef) <> (SELECT count(*) FROM ey) THEN RAISE EXCEPTION 'file missing'; END IF; END $$;",
     "-- guard: the DB years must still be what the snapshot saw",
     """DO $$ BEGIN IF EXISTS (SELECT 1 FROM ef WHERE (SELECT string_agg(start_year||'-'||end_year, ',' ORDER BY start_year) FROM file_years y WHERE y.file_id = ef.file_id) IS DISTINCT FROM ef.old) THEN RAISE EXCEPTION 'DB years changed since snapshot'; END IF; END $$;""",
     "DELETE FROM file_years y USING ef WHERE y.file_id = ef.file_id;",
     "INSERT INTO file_years (file_id, start_year, end_year) SELECT ef.file_id, split_part(r, '-', 1)::int, split_part(r, '-', 2)::int FROM ef, unnest(string_to_array(ef.new, ',')) r;",
     "SELECT 'files re-dated', count(*) FROM ef;"]
open(f"{H}/migration-e.sql", "w").write("\n".join(S) + "\n")
print("class E rows:", len(rows))
