"""Builds migration.sql (A–F) and migration-titles.sql (G) for ДАІФО/ДАЛуО/ДАОО/ДАПО from analysis/actions-*.json + DB snapshots."""
import json, csv, re, os
H = os.path.dirname(os.path.abspath(__file__)); A = f"{H}/analysis"
ARCHIVES = ["ДАІФО", "ДАЛуО", "ДАОО", "ДАПО"]
q = lambda s: "'" + str(s).replace("'", "''") + "'"
arr = lambda t: "ARRAY[" + ",".join(q(x) for x in t) + "]::text[]" if t else "'{}'::text[]"
yrs = lambda r: ",".join(f"{a}-{b}" for a, b in r)
GENERIC = re.compile(r"^(Церковні документи|Метричні книги Православних церков|Метричні книги$|Metrical Books and Clergy Records|Метричні книги,\s*Nobility|Nobility)", re.I)
DUPS = {"ДАЛуО": [("126-16-29339", "126-16-29"), ("126-16-31397", "126-16-31"), ("126-17-4413", "126-17-4"), ("126-27-383", "126-27-43"), ("126-30-6329", "126-30-6")],
        "ДАОО": [("921-1-16517", "921-1-16")]}
def title_for(church, tags, labels=()):
    if "метрична книга" in tags: return f"Метрична книга. {church}"
    lab = " ".join(labels).lower()
    if "обшук" in lab: return f"Книга шлюбних обшуків. {church}"
    if "сповід" in lab: return f"Сповідальні відомості. {church}"
    return f"{labels[0]}. {church}" if labels else church
S = ["-- Catalog т.4 reconciliation for ДАІФО / ДАЛуО / ДАОО / ДАПО. Generated by generate.py from analysis/actions-*.json.", "BEGIN;"]
T = ["-- G: replace placeholder titles with the catalog's church names (optional). Generated by generate.py.", "BEGIN;"]
P = S.append
mf, mt, my, mtitle, fy, dup, gen = [], [], [], [], [], [], []
for ar in ARCHIVES:
    act = json.load(open(f"{A}/actions-{ar}.json"))
    TYPO = {"ДАІФО": {"831": "631", "5941": "594"}, "ДАПО": {"101": "1011", "10111": "1011", "1001": "1011"}}.get(ar, {})
    PR = {}
    for k0, v in json.load(open(f"{A}/{ar}.json"))["refs"].items():   # same folding as compare_v4.py
        f, op, sp = k0.split("-"); PR.setdefault(f"{TYPO.get(f, f)}-{op.upper()}-{sp.upper()}", v)
    rows = {(r[0], r[1], r[2]): r for r in csv.reader(open(f"{A}/{ar}-files.tsv"), delimiter="\t", quoting=csv.QUOTE_NONE)}
    assert all(r[7] == f"{ar}-{k[0]}-{k[1]}-{k[2]}" for k, r in list(rows.items())[:50]), "full_code format"
    PRINT_TYPOS = {"ДАІФО": {"631-1-528Ь", "631-1-6837"}}.get(ar, set())   # "спр. 528ь" / "спр. 6837" = 528 / 683 in the book
    for m in act["missing_files"]:
        if m["code"] in PRINT_TYPOS: continue
        f, op, sp = m["code"].split("-"); lab = PR.get(m["code"], {}).get("labels", [])
        mf.append((ar, f, op, sp, title_for(m["church"], m["tags"], lab), m["tags"], yrs(m["years"])))
    for m in act["add_mk_tag"]: mt.append((f"{ar}-{m['code']}", m["tags"]))
    for m in act["fill_years"]: my.append((f"{ar}-{m['code']}", yrs(m["years"])))
    for m in act["fill_title"]:
        v = PR[m["code"]]; mtitle.append((f"{ar}-{m['code']}", title_for(m["church"], ["метрична книга"] if any(k in v["kinds"] for k in (5, 6, 7, 8)) else [], v["labels"])))
    for m in act["fond_years"]: fy.append((ar, m["code"], m["years"]))
    for s, d in DUPS.get(ar, []): dup.append((f"{ar}-{s}", f"{ar}-{d}"))
    for k, v in PR.items():
        r = rows.get(tuple(k.split("-")))
        if r and GENERIC.match(r[3] or ""): gen.append((f"{ar}-{k}", f"Метрична книга. {v['church']}"))
# ---- A: missing files
P("\n-- A. справи listed in the catalog but missing in the DB")
P("CREATE TEMP TABLE mf(archive text, fond text, inv text, code text, title text, tags text[], years text);")
P("INSERT INTO mf VALUES " + ",\n".join(f"({q(a)},{q(f)},{q(o)},{q(s)},{q(t)},{arr(tg)},{q(y)})" for a, f, o, s, t, tg, y in mf) + ";")
P("""INSERT INTO files (code, full_code, title, tags, inventory_id)
SELECT mf.code, mf.archive || '-' || mf.fond || '-' || mf.inv || '-' || mf.code, mf.title, mf.tags, i.id
FROM mf JOIN archives ar ON ar.code = mf.archive JOIN fonds fo ON fo.archive_id = ar.id AND fo.code = mf.fond JOIN inventories i ON i.fond_id = fo.id AND i.code = mf.inv
WHERE NOT EXISTS (SELECT 1 FROM files x WHERE x.inventory_id = i.id AND x.code = mf.code);""")
P("""INSERT INTO file_years (file_id, start_year, end_year) SELECT f.id, split_part(r, '-', 1)::int, split_part(r, '-', 2)::int
FROM mf JOIN files f ON f.full_code = mf.archive || '-' || mf.fond || '-' || mf.inv || '-' || mf.code, unnest(string_to_array(mf.years, ',')) r
WHERE mf.years <> '' AND NOT EXISTS (SELECT 1 FROM file_years y WHERE y.file_id = f.id) ON CONFLICT DO NOTHING;""")
P("DO $$ BEGIN IF (SELECT count(*) FROM mf JOIN files f ON f.full_code = mf.archive || '-' || mf.fond || '-' || mf.inv || '-' || mf.code) <> (SELECT count(*) FROM mf) THEN RAISE EXCEPTION 'A: not all files created (inventory missing?)'; END IF; END $$;")
# ---- B/C
P("\n-- B. «метрична книга» tag (+ record kinds) where the catalog says it is a metric book and the DB has no MK tag")
P("CREATE TEMP TABLE mt(full_code text, tags text[]); INSERT INTO mt VALUES " + ",\n".join(f"({q(k)},{arr(t)})" for k, t in mt) + ";")
P("UPDATE files f SET tags = (SELECT array_agg(DISTINCT x) FROM unnest(f.tags || mt.tags) x) FROM mt WHERE f.full_code = mt.full_code AND NOT ('метрична книга' = ANY(f.tags));")
P("\n-- C. bare years / titles")
if my:
    P("CREATE TEMP TABLE my(full_code text, years text); INSERT INTO my VALUES " + ",".join(f"({q(k)},{q(y)})" for k, y in my) + ";")
    P("INSERT INTO file_years (file_id, start_year, end_year) SELECT f.id, split_part(r, '-', 1)::int, split_part(r, '-', 2)::int FROM my JOIN files f ON f.full_code = my.full_code, unnest(string_to_array(my.years, ',')) r WHERE NOT EXISTS (SELECT 1 FROM file_years y WHERE y.file_id = f.id) ON CONFLICT DO NOTHING;")
if mtitle:
    P("CREATE TEMP TABLE mtt(full_code text, title text); INSERT INTO mtt VALUES " + ",".join(f"({q(k)},{q(t)})" for k, t in mtitle) + ";")
    P("UPDATE files f SET title = mtt.title FROM mtt WHERE f.full_code = mtt.full_code AND coalesce(f.title, '') = '';")
# ---- D
P("\n-- D. fond year ranges from the catalog header (fonds without any)")
P("CREATE TEMP TABLE fy(archive text, fond text, s int, e int); INSERT INTO fy VALUES " + ",".join(f"({q(a)},{q(c)},{s},{e})" for a, c, ys in fy for s, e in ys) + ";")
P("INSERT INTO fond_years (fond_id, start_year, end_year) SELECT fo.id, fy.s, fy.e FROM fy JOIN archives ar ON ar.code = fy.archive JOIN fonds fo ON fo.archive_id = ar.id AND fo.code = fy.fond WHERE NOT EXISTS (SELECT 1 FROM fond_years y WHERE y.fond_id = fo.id) ON CONFLICT DO NOTHING;")
# ---- E/F: duplicates + fond 5941
P("\n-- E. glued-code duplicates (identical title and year span as a catalog-listed sibling) + F. ДАІФО fond 5941 → 594-1-45")
P("CREATE TEMP TABLE mg(src text, dst text); INSERT INTO mg VALUES " + ",".join(f"({q(s)},{q(d)})" for s, d in dup) + ",('ДАІФО-5941-1-45','ДАІФО-594-1-45');")
P("CREATE TEMP TABLE g AS SELECT m.*, s.id AS src_id, d.id AS dst_id FROM mg m JOIN files s ON s.full_code = m.src JOIN files d ON d.full_code = m.dst;")
P("DO $$ BEGIN IF (SELECT count(*) FROM g) <> (SELECT count(*) FROM mg) THEN RAISE EXCEPTION 'E/F: source or target missing'; END IF; END $$;")
P("""DO $$ BEGIN IF EXISTS (SELECT 1 FROM g JOIN files s ON s.id = g.src_id JOIN files d ON d.id = g.dst_id
  WHERE g.src <> 'ДАІФО-5941-1-45' AND (s.title IS DISTINCT FROM d.title
     OR (SELECT min(start_year)||'-'||max(end_year) FROM file_years WHERE file_id = s.id) IS DISTINCT FROM (SELECT min(start_year)||'-'||max(end_year) FROM file_years WHERE file_id = d.id)))
  THEN RAISE EXCEPTION 'E: not an exact duplicate'; END IF; END $$;""")
P("DELETE FROM online_copies oc USING g WHERE oc.file_id = g.src_id AND EXISTS (SELECT 1 FROM online_copies d WHERE d.file_id = g.dst_id AND d.resource_id = oc.resource_id AND d.url = oc.url AND d.parsed = oc.parsed);")
P("UPDATE online_copies oc SET file_id = g.dst_id FROM g WHERE oc.file_id = g.src_id;")
P("INSERT INTO file_authors (file_id, author_id) SELECT g.dst_id, fa.author_id FROM file_authors fa JOIN g ON fa.file_id = g.src_id ON CONFLICT DO NOTHING;")
P("DELETE FROM file_authors fa USING g WHERE fa.file_id = g.src_id;")
P("UPDATE file_actions x SET file_id = g.dst_id FROM g WHERE x.file_id = g.src_id;")
P("UPDATE files d SET title = CASE WHEN coalesce(d.title,'') = '' THEN s.title ELSE d.title END, tags = CASE WHEN cardinality(d.tags) = 0 THEN s.tags ELSE d.tags END FROM g JOIN files s ON s.id = g.src_id WHERE d.id = g.dst_id;")
P("INSERT INTO file_years (file_id, start_year, end_year) SELECT g.dst_id, y.start_year, y.end_year FROM file_years y JOIN g ON y.file_id = g.src_id WHERE NOT EXISTS (SELECT 1 FROM file_years d WHERE d.file_id = g.dst_id) ON CONFLICT DO NOTHING;")
P("DELETE FROM files f USING g WHERE f.id = g.src_id;")
P("DELETE FROM inventories i USING fonds fo, archives ar WHERE i.fond_id = fo.id AND fo.archive_id = ar.id AND ar.code = 'ДАІФО' AND fo.code = '5941' AND NOT EXISTS (SELECT 1 FROM files WHERE inventory_id = i.id) AND NOT EXISTS (SELECT 1 FROM online_copies WHERE inventory_id = i.id);")
P("DELETE FROM fonds fo USING archives ar WHERE fo.archive_id = ar.id AND ar.code = 'ДАІФО' AND fo.code = '5941' AND NOT EXISTS (SELECT 1 FROM inventories WHERE fond_id = fo.id);")
P("DO $$ BEGIN IF EXISTS (SELECT 1 FROM fonds fo JOIN archives ar ON ar.id = fo.archive_id WHERE ar.code = 'ДАІФО' AND fo.code = '5941') THEN RAISE EXCEPTION 'F: fond 5941 still present'; END IF; END $$;")
P("""\nSELECT 'files created', count(*) FROM mf JOIN files f ON f.full_code = mf.archive || '-' || mf.fond || '-' || mf.inv || '-' || mf.code
UNION ALL SELECT 'files now MK-tagged', count(*) FROM mt JOIN files f ON f.full_code = mt.full_code WHERE 'метрична книга' = ANY(f.tags)
UNION ALL SELECT 'fond year rows', count(*) FROM fy JOIN archives ar ON ar.code = fy.archive JOIN fonds fo ON fo.archive_id = ar.id AND fo.code = fy.fond JOIN fond_years y ON y.fond_id = fo.id
UNION ALL SELECT 'duplicates gone', count(*) FROM mg WHERE NOT EXISTS (SELECT 1 FROM files WHERE full_code = mg.src);""")
open(f"{H}/migration.sql", "w").write("\n".join(S) + "\n")
# ---- G
T.append("CREATE TEMP TABLE gt(full_code text, title text);")
T.append("INSERT INTO gt VALUES " + ",\n".join(f"({q(k)},{q(t)})" for k, t in gen) + ";")
T.append("UPDATE files f SET title = gt.title FROM gt WHERE f.full_code = gt.full_code AND (f.title ~* '^(Церковні документи|Метричні книги Православних церков|Метричні книги$|Metrical Books and Clergy Records|Метричні книги,\\s*Nobility|Nobility)');")
T.append("-- church lines that already start with «Метричні книги …» (пароплави) must not get a second prefix")
T.append("UPDATE files f SET title = regexp_replace(f.title, '^Метрична книга\\. (Метричні книги )', '\\1') FROM gt WHERE f.full_code = gt.full_code AND f.title ~ '^Метрична книга\\. Метричні книги ';")
T.append("SELECT 'titles replaced', count(*) FROM gt JOIN files f ON f.full_code = gt.full_code WHERE f.title = gt.title;")
open(f"{H}/migration-titles.sql", "w").write("\n".join(T) + "\n")
with open(f"{H}/01-missing-files.csv", "w", newline="") as fh:
    w = csv.writer(fh); w.writerow(["archive", "fond", "inventory", "file", "title", "tags", "years"]); w.writerows([(a, f, o, s, t, "|".join(tg), y) for a, f, o, s, t, tg, y in mf])
with open(f"{H}/02-tags.csv", "w", newline="") as fh:
    w = csv.writer(fh); w.writerow(["full_code", "tags"]); w.writerows([(k, "|".join(t)) for k, t in mt])
with open(f"{H}/03-titles.csv", "w", newline="") as fh:
    w = csv.writer(fh); w.writerow(["full_code", "title"]); w.writerows(gen)
print(f"A files {len(mf)} | B tags {len(mt)} | C years {len(my)} titles {len(mtitle)} | D fond years {len(fy)} | E/F merges {len(dup)+1} | G titles {len(gen)}")
for x in mf: print("  A:", x[0], f"{x[1]}-{x[2]}-{x[3]}", "|", x[4][:60], "|", x[5], "|", x[6])
