-- Catalog т.4 reconciliation for ДАІФО / ДАЛуО / ДАОО / ДАПО. Generated by generate.py from analysis/actions-*.json.
BEGIN;

-- A. справи listed in the catalog but missing in the DB
CREATE TEMP TABLE mf(archive text, fond text, inv text, code text, title text, tags text[], years text);
INSERT INTO mf VALUES ('ДАЛуО','126','15','10','Метрична книга. Архангело-Михайлівська церква, с. Данилівка Старобільського пов.',ARRAY['метрична книга','народження','шлюб','смерть']::text[],''),
('ДАЛуО','126','15','14','Метрична книга. Архангело-Михайлівська церква, с. Данилівка Старобільського пов.',ARRAY['метрична книга','народження','шлюб','смерть']::text[],''),
('ДАЛуО','126','3','13','Метрична книга. Ганно-Зачатіївська церква, с. Павлівка Слов’яносербського пов. Павловської вол.',ARRAY['метрична книга','народження','шлюб','смерть']::text[],'1901-1901'),
('ДАЛуО','126','3','22','Метрична книга. Ганно-Зачатіївська церква, с. Павлівка Слов’яносербського пов. Павловської вол.',ARRAY['метрична книга','народження','шлюб','смерть']::text[],'1910-1910'),
('ДАЛуО','126','23','191','Метрична книга. Георгіївська церква, слоб. Можнякове Старобільського пов.',ARRAY['метрична книга','народження','шлюб','смерть']::text[],'1917-1917,1919-1919'),
('ДАЛуО','126','15','42','Метрична книга. Іоана-Предтеченська церква, слоб. Євсуг Старобільського пов.',ARRAY['метрична книга','народження','шлюб','смерть']::text[],'1895-1897'),
('ДАЛуО','126','30','34','Метрична книга. Костянтино-Оленівська церква, слоб. Караячна Старобільського пов.',ARRAY['метрична книга','народження']::text[],'1907-1913,1916-1917'),
('ДАЛуО','126','22','57','Метрична книга. Миколаївська церква, слоб. Новий Айдар Старобільського пов. Державний архів Луганської області',ARRAY['метрична книга','народження','шлюб','смерть']::text[],'1911-1915'),
('ДАЛуО','126','26','4','Метрична книга. Олександро-Невська церква, слоб. Нижня Дуванка Куп’янського пов.',ARRAY['метрична книга','народження','шлюб','смерть']::text[],'1894-1894,1899-1899'),
('ДАЛуО','126','18','111','Метрична книга. Петропавлівська церква, с. Юр’ївка Куп’янського пов.',ARRAY['метрична книга','народження','шлюб','смерть']::text[],'1909-1909'),
('ДАЛуО','126','30','108','Метрична книга. Покровська церква, слоб. Верхня Покровка Старобільського пов.',ARRAY['метрична книга','народження','шлюб','смерть']::text[],'1887-1888,1894-1897,1903-1903'),
('ДАЛуО','126','18','100','Метрична книга. Преображенська церква, слоб. Кремінна Куп’янського пов.',ARRAY['метрична книга','народження','шлюб','смерть']::text[],'1907-1909'),
('ДАЛуО','126','18','130','Метрична книга. Преображенська церква, слоб. Кремінна Куп’янського пов.',ARRAY['метрична книга','народження','шлюб','смерть']::text[],'1913-1915'),
('ДАЛуО','126','4','19','Метрична книга. Преображенська церква, с. Петрово-Красносілля Слав’яносербського пов.',ARRAY['метрична книга','шлюб']::text[],'1908-1914'),
('ДАЛуО','126','15','109','Метрична книга. Різдво-Богородична церква, слоб. Євсуг Старобільського пов.',ARRAY['метрична книга','народження','шлюб','смерть']::text[],'1917-1918'),
('ДАЛуО','126','15','118','Метрична книга. Свято-Духовна церква, слоб. Кононівка Старобільського пов.',ARRAY['метрична книга','народження','шлюб','смерть']::text[],'1899-1903'),
('ДАЛуО','126','30','157','Метрична книга. Тихонівська церква, слоб. Титарівка Старобільського пов.',ARRAY['метрична книга','народження','шлюб','смерть']::text[],'1872-1873,1882-1883'),
('ДАЛуО','126','30','165','Метрична книга. Тихонівська церква, слоб. Титарівка Старобільського пов.',ARRAY['метрична книга','народження','шлюб','смерть']::text[],'1915-1917,1919-1919'),
('ДАЛуО','126','23','171','Метрична книга. Троїцька церква, слоб. Ново-Россош Старобільського пов.',ARRAY['метрична книга','народження','шлюб','смерть']::text[],'1903-1903,1907-1907'),
('ДАЛуО','126','4','26','Метрична книга. Успенська церква, с. Хрустальне Амвросіївського благочинія Слав’яносербського пов.',ARRAY['метрична книга','народження']::text[],'1916-1917'),
('ДАЛуО','126','30','43','Метрична книга. Христовоздвиженська церква, слоб. Байдівка Старобільського пов.',ARRAY['метрична книга','народження','шлюб','смерть']::text[],'1898-1899,1909-1909'),
('ДАЛуО','126','1','106','Метрична книга. Лютеранська церква, м. Луганськ',ARRAY['метрична книга','народження']::text[],'1915-1920'),
('ДАОО','39','1','129','Листування про різних осіб, що вступали у шлюб. Синагога, м. Одеса','{}'::text[],'1910-1915');
INSERT INTO files (code, full_code, title, tags, inventory_id)
SELECT mf.code, mf.archive || '-' || mf.fond || '-' || mf.inv || '-' || mf.code, mf.title, mf.tags, i.id
FROM mf JOIN archives ar ON ar.code = mf.archive JOIN fonds fo ON fo.archive_id = ar.id AND fo.code = mf.fond JOIN inventories i ON i.fond_id = fo.id AND i.code = mf.inv
WHERE NOT EXISTS (SELECT 1 FROM files x WHERE x.inventory_id = i.id AND x.code = mf.code);
INSERT INTO file_years (file_id, start_year, end_year) SELECT f.id, split_part(r, '-', 1)::int, split_part(r, '-', 2)::int
FROM mf JOIN files f ON f.full_code = mf.archive || '-' || mf.fond || '-' || mf.inv || '-' || mf.code, unnest(string_to_array(mf.years, ',')) r
WHERE mf.years <> '' AND NOT EXISTS (SELECT 1 FROM file_years y WHERE y.file_id = f.id) ON CONFLICT DO NOTHING;
DO $$ BEGIN IF (SELECT count(*) FROM mf JOIN files f ON f.full_code = mf.archive || '-' || mf.fond || '-' || mf.inv || '-' || mf.code) <> (SELECT count(*) FROM mf) THEN RAISE EXCEPTION 'A: not all files created (inventory missing?)'; END IF; END $$;

-- B. «метрична книга» tag (+ record kinds) where the catalog says it is a metric book and the DB has no MK tag
CREATE TEMP TABLE mt(full_code text, tags text[]); INSERT INTO mt VALUES ('ДАІФО-631-1-116',ARRAY['метрична книга','народження']::text[]),
('ДАІФО-631-1-117',ARRAY['метрична книга','шлюб']::text[]),
('ДАІФО-631-1-442',ARRAY['метрична книга','народження']::text[]),
('ДАІФО-594-1-45',ARRAY['метрична книга','шлюб']::text[]),
('ДАІФО-631-1-4',ARRAY['метрична книга','народження']::text[]),
('ДАІФО-631-1-697',ARRAY['метрична книга','шлюб']::text[]),
('ДАІФО-631-1-81',ARRAY['метрична книга','шлюб']::text[]),
('ДАІФО-631-1-98',ARRAY['метрична книга','смерть']::text[]),
('ДАІФО-631-1-114',ARRAY['метрична книга','смерть']::text[]),
('ДАІФО-631-1-133',ARRAY['метрична книга','смерть']::text[]),
('ДАІФО-631-1-137',ARRAY['метрична книга','смерть']::text[]),
('ДАІФО-631-1-317',ARRAY['метрична книга','народження']::text[]),
('ДАІФО-631-1-327А',ARRAY['метрична книга','шлюб']::text[]),
('ДАІФО-631-1-360',ARRAY['метрична книга','народження']::text[]),
('ДАІФО-631-1-66',ARRAY['метрична книга','народження']::text[]),
('ДАІФО-631-1-370',ARRAY['метрична книга','шлюб']::text[]),
('ДАІФО-631-1-489',ARRAY['метрична книга','смерть']::text[]),
('ДАІФО-631-1-491',ARRAY['метрична книга','народження','шлюб','смерть']::text[]),
('ДАІФО-631-1-494',ARRAY['метрична книга','народження']::text[]),
('ДАІФО-631-1-495',ARRAY['метрична книга','шлюб','смерть']::text[]),
('ДАІФО-631-1-23',ARRAY['метрична книга','народження','шлюб','смерть']::text[]),
('ДАІФО-631-1-241',ARRAY['метрична книга','шлюб']::text[]),
('ДАІФО-631-1-242',ARRAY['метрична книга','смерть']::text[]),
('ДАІФО-631-1-244',ARRAY['метрична книга','шлюб']::text[]),
('ДАІФО-631-1-273',ARRAY['метрична книга','шлюб']::text[]),
('ДАІФО-631-1-274',ARRAY['метрична книга','смерть']::text[]),
('ДАІФО-631-1-285',ARRAY['метрична книга','шлюб']::text[]),
('ДАІФО-631-1-286',ARRAY['метрична книга','смерть']::text[]),
('ДАІФО-631-1-486',ARRAY['метрична книга','смерть']::text[]),
('ДАІФО-631-1-558',ARRAY['метрична книга','смерть']::text[]),
('ДАІФО-631-1-571',ARRAY['метрична книга','народження']::text[]),
('ДАІФО-631-1-585',ARRAY['метрична книга','смерть']::text[]),
('ДАІФО-631-1-759',ARRAY['метрична книга','народження']::text[]),
('ДАІФО-631-1-636',ARRAY['метрична книга','шлюб']::text[]),
('ДАІФО-631-1-647',ARRAY['метрична книга','народження']::text[]),
('ДАОО-37-13-883',ARRAY['метрична книга','смерть']::text[]),
('ДАОО-37-3-1343',ARRAY['метрична книга','народження','шлюб','смерть']::text[]),
('ДАОО-37-13-1211',ARRAY['метрична книга','народження']::text[]),
('ДАОО-37-3А-65',ARRAY['метрична книга','народження','шлюб','смерть']::text[]),
('ДАОО-37-13-1152',ARRAY['метрична книга','народження','шлюб','смерть']::text[]),
('ДАОО-628-1-4',ARRAY['метрична книга','шлюб']::text[]),
('ДАОО-39-4-1',ARRAY['метрична книга','народження']::text[]),
('ДАОО-39-4-15',ARRAY['метрична книга','народження']::text[]),
('ДАОО-39-4-23',ARRAY['метрична книга','народження']::text[]),
('ДАОО-39-4-30',ARRAY['метрична книга','народження']::text[]),
('ДАОО-39-5-11',ARRAY['метрична книга','народження']::text[]),
('ДАОО-39-5-103',ARRAY['метрична книга','народження']::text[]),
('ДАОО-39-5-107',ARRAY['метрична книга','народження']::text[]),
('ДАОО-39-5-131',ARRAY['метрична книга','народження']::text[]),
('ДАОО-39-5-138',ARRAY['метрична книга','народження']::text[]),
('ДАОО-39-5-142',ARRAY['метрична книга','народження']::text[]),
('ДАОО-39-5-149',ARRAY['метрична книга','народження']::text[]),
('ДАОО-39-5-161',ARRAY['метрична книга','шлюб']::text[]),
('ДАОО-39-5-165',ARRAY['метрична книга','шлюб']::text[]),
('ДАОО-920-1-14',ARRAY['метрична книга','народження']::text[]),
('ДАОО-920-1-56',ARRAY['метрична книга','народження']::text[]),
('ДАПО-1011-3-98',ARRAY['метрична книга','народження','шлюб','смерть']::text[]),
('ДАПО-1011-6-57',ARRAY['метрична книга','народження','шлюб','смерть']::text[]),
('ДАПО-1011-6-141',ARRAY['метрична книга','народження','шлюб','смерть']::text[]),
('ДАПО-1011-6-178',ARRAY['метрична книга','народження','шлюб']::text[]),
('ДАПО-1011-6-213',ARRAY['метрична книга','народження','шлюб','смерть']::text[]),
('ДАПО-706-3-1',ARRAY['метрична книга','народження']::text[]),
('ДАПО-1011-6-18',ARRAY['метрична книга','народження','шлюб','смерть']::text[]),
('ДАПО-1011-8-12',ARRAY['метрична книга','народження']::text[]),
('ДАПО-1011-6-296',ARRAY['метрична книга','народження','шлюб','смерть']::text[]),
('ДАПО-1011-9-103',ARRAY['метрична книга','народження','шлюб','смерть']::text[]),
('ДАПО-1011-9-46',ARRAY['метрична книга','народження','шлюб','розлучення']::text[]),
('ДАПО-1011-9-49',ARRAY['метрична книга','народження','шлюб','розлучення']::text[]),
('ДАПО-1011-9-52',ARRAY['метрична книга','народження','шлюб','смерть']::text[]),
('ДАПО-1011-3-21',ARRAY['метрична книга','народження','шлюб','смерть']::text[]),
('ДАПО-1011-6-386',ARRAY['метрична книга','народження','шлюб','смерть']::text[]),
('ДАПО-1011-6-392',ARRAY['метрична книга','народження','шлюб','смерть']::text[]),
('ДАПО-1011-6-408',ARRAY['метрична книга','народження','шлюб','смерть']::text[]),
('ДАПО-1011-6-418',ARRAY['метрична книга','народження','шлюб','смерть']::text[]),
('ДАПО-1011-6-424',ARRAY['метрична книга','народження','шлюб','смерть']::text[]),
('ДАПО-1011-6-475',ARRAY['метрична книга','народження','шлюб','смерть']::text[]),
('ДАПО-1011-6-521',ARRAY['метрична книга','народження','шлюб','смерть']::text[]),
('ДАПО-1011-6-604',ARRAY['метрична книга','народження','шлюб','смерть']::text[]),
('ДАПО-1011-3-110',ARRAY['метрична книга','народження','смерть']::text[]),
('ДАПО-1011-6-665',ARRAY['метрична книга','народження','шлюб','смерть']::text[]),
('ДАПО-1011-5-170',ARRAY['метрична книга','народження']::text[]),
('ДАПО-1011-6-976',ARRAY['метрична книга','народження','шлюб','смерть']::text[]),
('ДАПО-1011-8-115',ARRAY['метрична книга','народження','шлюб','смерть']::text[]),
('ДАПО-1011-6-1164',ARRAY['метрична книга','народження','шлюб','смерть']::text[]),
('ДАПО-1011-6-1189',ARRAY['метрична книга','народження','шлюб','смерть']::text[]);
UPDATE files f SET tags = (SELECT array_agg(DISTINCT x) FROM unnest(f.tags || mt.tags) x) FROM mt WHERE f.full_code = mt.full_code AND NOT ('метрична книга' = ANY(f.tags));

-- C. bare years / titles
CREATE TEMP TABLE my(full_code text, years text); INSERT INTO my VALUES ('ДАІФО-594-1-45','1843-1867');
INSERT INTO file_years (file_id, start_year, end_year) SELECT f.id, split_part(r, '-', 1)::int, split_part(r, '-', 2)::int FROM my JOIN files f ON f.full_code = my.full_code, unnest(string_to_array(my.years, ',')) r WHERE NOT EXISTS (SELECT 1 FROM file_years y WHERE y.file_id = f.id) ON CONFLICT DO NOTHING;
CREATE TEMP TABLE mtt(full_code text, title text); INSERT INTO mtt VALUES ('ДАІФО-594-1-45','Метрична книга. Костел, с. Турка Коломийського пов.');
UPDATE files f SET title = mtt.title FROM mtt WHERE f.full_code = mtt.full_code AND coalesce(f.title, '') = '';

-- D. fond year ranges from the catalog header (fonds without any)
CREATE TEMP TABLE fy(archive text, fond text, s int, e int); INSERT INTO fy VALUES ('ДАОО','4',1795,1920),('ДАОО','37',1776,1919),('ДАОО','315',1884,1920),('ДАОО','731',1849,1917);
INSERT INTO fond_years (fond_id, start_year, end_year) SELECT fo.id, fy.s, fy.e FROM fy JOIN archives ar ON ar.code = fy.archive JOIN fonds fo ON fo.archive_id = ar.id AND fo.code = fy.fond WHERE NOT EXISTS (SELECT 1 FROM fond_years y WHERE y.fond_id = fo.id) ON CONFLICT DO NOTHING;

-- E. glued-code duplicates (identical title and year span as a catalog-listed sibling) + F. ДАІФО fond 5941 → 594-1-45
CREATE TEMP TABLE mg(src text, dst text); INSERT INTO mg VALUES ('ДАЛуО-126-16-29339','ДАЛуО-126-16-29'),('ДАЛуО-126-16-31397','ДАЛуО-126-16-31'),('ДАЛуО-126-17-4413','ДАЛуО-126-17-4'),('ДАЛуО-126-27-383','ДАЛуО-126-27-43'),('ДАЛуО-126-30-6329','ДАЛуО-126-30-6'),('ДАОО-921-1-16517','ДАОО-921-1-16'),('ДАІФО-5941-1-45','ДАІФО-594-1-45');
CREATE TEMP TABLE g AS SELECT m.*, s.id AS src_id, d.id AS dst_id FROM mg m JOIN files s ON s.full_code = m.src JOIN files d ON d.full_code = m.dst;
DO $$ BEGIN IF (SELECT count(*) FROM g) <> (SELECT count(*) FROM mg) THEN RAISE EXCEPTION 'E/F: source or target missing'; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM g JOIN files s ON s.id = g.src_id JOIN files d ON d.id = g.dst_id
  WHERE g.src <> 'ДАІФО-5941-1-45' AND (s.title IS DISTINCT FROM d.title
     OR (SELECT min(start_year)||'-'||max(end_year) FROM file_years WHERE file_id = s.id) IS DISTINCT FROM (SELECT min(start_year)||'-'||max(end_year) FROM file_years WHERE file_id = d.id)))
  THEN RAISE EXCEPTION 'E: not an exact duplicate'; END IF; END $$;
DELETE FROM online_copies oc USING g WHERE oc.file_id = g.src_id AND EXISTS (SELECT 1 FROM online_copies d WHERE d.file_id = g.dst_id AND d.resource_id = oc.resource_id AND d.url = oc.url AND d.parsed = oc.parsed);
UPDATE online_copies oc SET file_id = g.dst_id FROM g WHERE oc.file_id = g.src_id;
INSERT INTO file_authors (file_id, author_id) SELECT g.dst_id, fa.author_id FROM file_authors fa JOIN g ON fa.file_id = g.src_id ON CONFLICT DO NOTHING;
DELETE FROM file_authors fa USING g WHERE fa.file_id = g.src_id;
UPDATE file_actions x SET file_id = g.dst_id FROM g WHERE x.file_id = g.src_id;
UPDATE files d SET title = CASE WHEN coalesce(d.title,'') = '' THEN s.title ELSE d.title END, tags = CASE WHEN cardinality(d.tags) = 0 THEN s.tags ELSE d.tags END FROM g JOIN files s ON s.id = g.src_id WHERE d.id = g.dst_id;
INSERT INTO file_years (file_id, start_year, end_year) SELECT g.dst_id, y.start_year, y.end_year FROM file_years y JOIN g ON y.file_id = g.src_id WHERE NOT EXISTS (SELECT 1 FROM file_years d WHERE d.file_id = g.dst_id) ON CONFLICT DO NOTHING;
DELETE FROM files f USING g WHERE f.id = g.src_id;
DELETE FROM inventories i USING fonds fo, archives ar WHERE i.fond_id = fo.id AND fo.archive_id = ar.id AND ar.code = 'ДАІФО' AND fo.code = '5941' AND NOT EXISTS (SELECT 1 FROM files WHERE inventory_id = i.id) AND NOT EXISTS (SELECT 1 FROM online_copies WHERE inventory_id = i.id);
DELETE FROM fonds fo USING archives ar WHERE fo.archive_id = ar.id AND ar.code = 'ДАІФО' AND fo.code = '5941' AND NOT EXISTS (SELECT 1 FROM inventories WHERE fond_id = fo.id);
DO $$ BEGIN IF EXISTS (SELECT 1 FROM fonds fo JOIN archives ar ON ar.id = fo.archive_id WHERE ar.code = 'ДАІФО' AND fo.code = '5941') THEN RAISE EXCEPTION 'F: fond 5941 still present'; END IF; END $$;

SELECT 'files created', count(*) FROM mf JOIN files f ON f.full_code = mf.archive || '-' || mf.fond || '-' || mf.inv || '-' || mf.code
UNION ALL SELECT 'files now MK-tagged', count(*) FROM mt JOIN files f ON f.full_code = mt.full_code WHERE 'метрична книга' = ANY(f.tags)
UNION ALL SELECT 'fond year rows', count(*) FROM fy JOIN archives ar ON ar.code = fy.archive JOIN fonds fo ON fo.archive_id = ar.id AND fo.code = fy.fond JOIN fond_years y ON y.fond_id = fo.id
UNION ALL SELECT 'duplicates gone', count(*) FROM mg WHERE NOT EXISTS (SELECT 1 FROM files WHERE full_code = mg.src);
